### ISSUE TITLE
Bug in latest Version

### ISSUE THREAD

**Issue by sschmocker** [Romanitho/Winget-Install#40] opened 2022-05-13 08:03 UTC
I think the new version got an error:
`###################################	#                                 #	#         Winget Install          #	#                                 #	###################################Log path is: C:\MDM\winget\install.log10:01:23 - ###   5/13/2022 - NEW INSTALL REQUEST   ###PS>TerminatingError(Out-File): "Could not find a part of the path 'C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WinGet\Settings\settings.json'."Out-File : Could not find a part of the path 'C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WinGet\Settings\settings.json'.At C:\Windows\IMECache\e351148d-8d6b-4a5a-bc26-dfc47700f498_3\CockpitAgent-Chrome.ps1:104 char:36+ ...   $ConfigFile | ConvertTo-Json | Out-File $path -Encoding utf8 -Force+                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~    + CategoryInfo          : OpenError: (:) [Out-File], DirectoryNotFoundException    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommandOut-File : Could not find a part of the path'C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WinGet\Settings\settings.json'.At C:\Windows\IMECache\e351148d-8d6b-4a5a-bc26-dfc47700f498_3\CockpitAgent-Chrome.ps1:104 char:36+ ...   $ConfigFile | ConvertTo-Json | Out-File $path -Encoding utf8 -Force+                                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~    + CategoryInfo          : OpenError: (:) [Out-File], DirectoryNotFoundException    + FullyQualifiedErrorId : FileOpenFailure,Microsoft.PowerShell.Commands.OutFileCommand10:01:24 - Using following Winget Cmd: C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.18.431.0_x64__8wekyb3d8bbwe\winget.exe10:01:25 - Google.Chrome exists on Winget Repository.10:01:26 - Installing Google.Chrome...C:\Program : The term 'C:\Program' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.At line:1 char:1+ C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.18.431.0 ...+ ~~~~~~~~~~    + CategoryInfo          : ObjectNotFound: (C:\Program:String) [], CommandNotFoundException    + FullyQualifiedErrorId : CommandNotFoundExceptionC:\Program : The term 'C:\Program' is not recognized as the name of a cmdlet, function, script file, or operableprogram. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.At line:1 char:1+ C:\Program Files\WindowsApps\Microsoft.DesktopAppInstaller_1.18.431.0 ...+ ~~~~~~~~~~    + CategoryInfo          : ObjectNotFound: (C:\Program:String) [], CommandNotFoundException    + FullyQualifiedErrorId : CommandNotFoundException10:01:26 - Google.Chrome installation failed!10:01:28 - ###   END REQUEST   ###**********************Windows PowerShell transcript endEnd time: 20220513100130**********************`

**Comment by Romanitho** [comment] 2022-05-13 08:49
I cannot reproduce. What commande do you run ?

**Comment by sschmocker** [comment] 2022-05-13 09:07
Currently im looking into it. Maybe its because of the encoding. Im Using some mods on top of your script to push the output to a teams webhook

**Comment by sschmocker** [comment] 2022-05-13 10:27
So far the script fully works even with my code, so that should not be the problem. 
The error only occurs if i push it via intune not if i run the script manualy on a machine 
Are you also testing via Intune?

**Comment by sschmocker** [comment] 2022-05-16 07:36
I downloaded your latest script and pushed it via intune without my mods. its not working anymore and its also not writing logs so i cant post an output error.
Install command: powershell.exe -ExecutionPolicy Bypass -File winget-install.ps1 -AppIDs Notepad++.Notepad++

**Comment by Romanitho** [comment] 2022-05-17 06:46
Works for me:  
![image](https://user-images.githubusercontent.com/96626929/168746478-f6621362-fb98-408a-8b5f-d04f753d9be2.png)

**Comment by sschmocker** [comment] 2022-05-17 07:43
Yes, runned manually it works. but as soon as I push it to intune its not working on the device for me

**Comment by Romanitho** [comment] 2022-05-17 09:31
Oh... can you try to install latest preview version of Winget on the device you are testing ? We encountered a similar issue when running under system context with @KnifMelti on current Winget prod version.

**Comment by sschmocker** [comment] 2022-05-17 09:36
I tried both previews, 1.3.431 and1.3.1251. its not working on either version. Before the update of the script it worked fine.

**Comment by Romanitho** [comment] 2022-05-17 09:40
Ok. Can you use the script that work for you so far, i'll make more tests with intune this afternoon (Paris time)

**Comment by sschmocker** [comment] 2022-05-17 09:42
Sure i use the one that worked for me

**Comment by Romanitho** [comment] 2022-05-17 10:57
do you use the script in the 1.6 version, or the script from "main" branch ? cause I don't have issue in latest version (1.6) but I have one in the "main" one that i need to fix

**Comment by sschmocker** [comment] 2022-05-17 11:08
Im using the script from main branch there is the error.
I Just tested 1.6 and it works fine. thx for clarification

**Comment by Romanitho** [comment] 2022-05-17 11:10
main one will be fixed, thanks for spotting the issue anyway ;)

**Comment by Romanitho** [comment] 2022-05-17 22:36
Made few changes in PR #42 
Could you eventually test this new version (in the main branch ☺️)
If everything works, I'll publish new version

**Comment by sschmocker** [comment] 2022-05-18 07:29
yeah sure! tested it and it works flawless ☺️

**Comment by Romanitho** [comment] 2022-05-18 09:09
Nice. Even with `--override` argument ? If you approve, i'll publish new release as we have better logs now

**Closed** 2022-07-08 11:39 UTC
